crucible_print_servers:
  hosts:
#    131.243.182.179: #crucible-print1.dhcp.lbl.gov: 
#      print_id: print1
#      hardware: rpi4-2GB
    crucible-print-ucd1.ts.mfdata.org:
      print_id: ucd1
      hardware: rpi4-2GB      
    crucible-print-b30-113.ts.mfdata.org: #crucible-print-b30-113.dhcp.lbl.gov:
      print_id: b30-113
      hardware: rpi3
  vars:
    ansible_user: lab